apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1 # Start with 1 replica
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: <ACR_LOGIN_SERVER>/backend:latest # Placeholder - CI/CD replaces this
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: app-secrets # Load secrets as environment variables
        resources: # Request minimal resources
          requests:
            cpu: "100m" # 0.1 vCPU
            memory: "256Mi"
          limits:
            cpu: "500m" # 0.5 vCPU
            memory: "512Mi"
        readinessProbe: # Check if app is ready to serve traffic
          httpGet:
            path: /health # Your health check endpoint
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe: # Check if app is still alive
          httpGet:
            path: /health # Your health check endpoint
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80 # Service port
      targetPort: 8000 # Container port
  type: ClusterIP # Only reachable within the cluster