apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1 # Start with 1 replica
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: <ACR_LOGIN_SERVER>/backend:latest # Placeholder - CI/CD replaces this
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST)/$(DB_NAME)"
        - name: REDIS_CONNECTION_STRING
          value: "rediss://:$(REDIS_PASSWORD)@$(REDIS_HOST):$(REDIS_PORT)/0?ssl_cert_reqs=none"
        - name: FRONTEND_BASE_URL
          value: "http://$(FRONTEND_URL)"  # Use environment variable substitution
        - name: PUBLIC_URL
          value: "http://$(FRONTEND_URL)"  # Use environment variable substitution
        envFrom:
        - secretRef:
            name: app-secrets # Load secrets as environment variables
        resources: # Request minimal resources
          requests:
            cpu: "100m" # 0.1 vCPU
            memory: "256Mi"
          limits:
            cpu: "500m" # 0.5 vCPU
            memory: "512Mi"
        readinessProbe: # Check if app is ready to serve traffic
          httpGet:
            path: /api/health # Your health check endpoint
            port: 8000
          initialDelaySeconds: 60 # Increase from 15 to 30 to give more startup time
          periodSeconds: 10
          timeoutSeconds: 5 # Increase timeout value
        livenessProbe: # Check if app is still alive
          httpGet:
            path: /api/health # Your health check endpoint
            port: 8000
          initialDelaySeconds: 120 # Increase from 30 to 60
          periodSeconds: 20
          timeoutSeconds: 5 # Increase timeout value

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80 # Service port
      targetPort: 8000 # Container port
  type: ClusterIP # Only reachable within the cluster