apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1 # Start with 1 replica
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: <ACR_LOGIN_SERVER>/frontend:latest # Placeholder - CI/CD replaces this
        ports:
        - containerPort: 80
        env: # Pass backend service URL to frontend if needed
        - name: REACT_APP_API_URL # Example variable name
          value: "http://backend-service" # Internal Kubernetes DNS name
        resources: # Request minimal resources
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /health.html # Or your actual health check path
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health.html # Or your actual health check path
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # Expose frontend externally with an Azure Load Balancer
                     # This will provision a Public IP address (costs money)